// import type { Metadata } from 'next'
import { DM_Sans } from 'next/font/google'
import Header from '@/components/header/Header'
import './../globals.css'

const dm = DM_Sans({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Phase-r',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${dm.className}`}>
        <Header />
        <div className='hidden lg:block xl:block'>
          {/* <Sidebar /> */}
        </div>
        {children}
      </body>
    </html>
  )
}
